version: "3.1"

services:
    media-goggler:
        build: .
        image: media-goggler
        networks:
            - goggler
        volumes:
            - /media:/media
        ports:
            - "80:3000"

    neo4j:
        image: neo4j:3.3
        networks:
            - goggler
# If you want a persistant database
        volumes:
            - /home/jan/neo4j/data:/data
        ports:
            - "7687:7687"

networks:
    goggler:
