version: "3.1"

services:
    media-goggler:
        build: .
        image: media-goggler
        networks:
            - goggler
        volumes:
            - /media:/media
        ports:
            - "80:3000"

    neo4j:
        image: neo4j:3.3
        networks:
            - goggler

networks:
    goggler:
