name: media-goggler
version: 0.0.1
synopsis: A media server written in Haskell
description: See README at <https://github.com/jvanbruegge/media-goggler#readme>
maintainer: Jan van Brügge <supermanitu@gmail.com>
license: Apache-2.0
github: jvanbruegge/media-goggler
category: Web

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

dependencies:
  - aeson
  - base
  - bytestring
  - clay
  - conduit
  - containers
  - data-default
  - filepath
  - hasbolt
  - http-media
  - lucid
  - path
  - path-io
  - protolude
  - resource-pool
  - resourcet
  - servant-clay
  - servant-lucid
  - servant-server
  - string-conversions
  - text
  - unix-compat
  - unordered-containers
  - uuid
  - wai
  - warp

executable:
  main: Main.hs
  source-dirs: src

default-extensions:
    - AutoDeriveTypeable
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveAnyClass
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DerivingStrategies
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - ExistentialQuantification
    - ExplicitForAll
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GADTs
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - KindSignatures
    - LambdaCase
    - MultiParamTypeClasses
    - MultiWayIf
    - NamedFieldPuns
    - NoImplicitPrelude
    - OverloadedStrings
    - PartialTypeSignatures
    - PatternGuards
    - PolyKinds
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeOperators
    - TypeSynonymInstances
    - ViewPatterns
